"""User fields modified

Revision ID: 55582a8dafc5
Revises: 1f42d8902ed0
Create Date: 2020-07-02 21:44:48.890982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55582a8dafc5'
down_revision = '1f42d8902ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'name',
        sa.VARCHAR(length=150),
        autoincrement=False,
        nullable=True
    )
    )
    op.add_column('users', sa.Column('email', sa.VARCHAR(
        length=150), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
